"""empty message

Revision ID: 38e9ee7b8031
Revises: bb596a26c961
Create Date: 2024-01-17 18:50:57.019413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e9ee7b8031'
down_revision = 'bb596a26c961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('report_rating',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('report_rating',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('response',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###
